version: '3.10'

services:
  db:
    image: postgres:15.2
    container_name: online_shop_postgres
    restart: always
    environment:
      POSTGRES_DB: online_shop
      POSTGRES_USER: Pablo
      POSTGRES_PASSWORD: Ppablo10
    ports:
      - "5433:5432"
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql

  cache-db:
    image: redis:6.2-alpine
    container_name: online_shop_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass Ppablo10

  document-db:
    image: mongo:6.0.4
    restart: always
    container_name: online_shop_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: Pablo
      MONGO_INITDB_ROOT_PASSWORD: Ppablo10
      MONGO_INITDB_DATABASE: onlineShop
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
